An early implementation of basefunctions for databasemanagement.
TDDD96-G11-BLHub/dbman pull request #2
Opened 2024-04-08 06:51 UTC by MattKa01

Function for setting up a connection, searching for documents and deleting documents. Most of the documentvalues are hardcoded but can be changed if you want to use the code for testing. Also see the README for instructions on usage.

2024-04-08 11:51 UTC, MekkerMax approved these changes, later dismissed

2024-04-09 14:06 UTC, Jacalz requested changes
I added a few comments inline. I would also appreciate if the "lib" package gets renamed to something better describing. It would also be nice to avoid panics and instead have functions return error values.

2024-04-09 14:06 UTC, Jacalz commented on lib/db_function_enum.go
> +	FnFindOne DBFunction = iota + 1 //EnumIndex = 1
If you don't have a need for it to start on 1, start on 0.

2024-04-09 14:06 UTC, Jacalz commented on lib/db_function_enum.go
> +	FnFindAll //EnumIndex = 7
You can remove the comments with index. You should not hard-code the numbers to the index is irrelevant.

2024-04-09 14:06 UTC, Jacalz commented on lib/db_function_enum.go
> +type DBFunction int
Public types should have a doc comment.

2024-04-09 14:06 UTC, Jacalz commented on lib/db_update.go
> +}
```suggestion
func DropDatabase(client mongo.Client, database string) error {
        return client.Database(database).Drop(context.TODO())
}
```

2024-04-09 14:06 UTC, Jacalz commented on lib/db_function_enum.go
> +}
Why? The type is an int already.

2024-04-09 14:06 UTC, Jacalz commented on lib/db_fetch.go
> +}
Remove test print please

2024-04-09 14:12 UTC, Jacalz requested changes

2024-04-09 14:12 UTC, Jacalz commented on main.go
> +	lib.TestConnection(*client)
Doing `*client` grabs the value and copies it. Should the function take a `*mongo.Client` instead.

2024-04-09 14:26 UTC, Jacalz requested changes

2024-04-09 14:26 UTC, Jacalz commented on lib/db_fetch.go
> +func FetchDocument(client mongo.Client, database string, collection string, filter bson.D, fn DBFunction) []byte {
`fn DBFunction` can probably be `many bool`.

2024-04-09 14:26 UTC, Jacalz commented on lib/db_info.go
> +	if err := client.Database("admin").RunCommand(context.TODO(), bson.D{{"ping", 1}}).Decode(&result); err != nil {
TODO: We might want to use a context with timeout.

2024-04-09 14:26 UTC, Jacalz commented on lib/db_update.go
> +func InsertDocument(client mongo.Client, database string, collection string, document bson.D, docs []interface{}, fn DBFunction) {
```suggestion
func InsertDocument(client mongo.Client, database string, collection string, document bson.D, docs []any, fn DBFunction) {
```

2024-04-10 07:52 UTC, MattKa01 commented
All the comments have pretty much been handled. Currently the client object is used the same way since I need to read more into it before making changes. The program will also still panic upon a error which is good for testing but will be changed to slog after reading the documentation.

The enum has been removed and seperate functions for the one/many calls have been implemented.

The lib package has been renamed to db

2024-04-11 09:59 UTC, Jacalz requested changes
Thanks. This is looking a lot better. I have one comment inline that wasn't fixed from my older set of review comments.

2024-04-11 09:59 UTC, Jacalz commented on db/db_update.go
> +func DeleteManyDocuments(client mongo.Client, database string, collection string, filter bson.D) {
I am pretty sure that all of these functions should take a `client *mongo.Client` as it is what is returned from `mongo.Connect`. All of the `*client` dereferences when calling the functions makes me very nervous.

2024-04-11 10:00 UTC, Jacalz commented
You need to rebase on main and fix the merge conflicts. Once the workflows are passing and the comment above is resolved, this should be ready to be merged.

2024-04-16 08:46 UTC, Jacalz commented
go install mvdan.cc/gofumpt@latest

gofumpt -w .

2024-04-16 09:28 UTC, Jacalz approved these changes

2024-04-16 09:28 UTC, merged